connectedin/connectedin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
]

connectedin/perfis/urls.py
from django.conf.urls import url
from perfis import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^perfis/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
    url(r'^perfis/(?P<perfil_id>\d+)/convidar$', views.convidar, name='convidar'),
    url(r'^convite/(?P<convite_id>\d+)/aceitar$', views.aceitar, name='aceitar'),
]

connectedin/usuarios/urls.py
from django.conf.urls import url
from usuarios.views import RegistrarUsuarioView


urlpatterns = [
    url(r'^registrar/$',RegistrarUsuarioView.as_view(), name='registrar'),
]

connectedin/perfis/models.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, related_name="perfil")

    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        Convite(solicitante=self, convidado=perfil_convidado).save()


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.delete()

connectedin/usuarios/models.py
from django.db import models

# Create your models here.

connectedin/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.data['nome']).exists()

        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False

        return valid


    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

connectedin/perfis/views.py
from django.shortcuts import render, redirect
from perfis.models import Perfil, Convite


def index(request):
    return render(request, 'perfis/index.html',
                  {'perfis': Perfil.objects.all(), 'perfil_logado': get_perfil_logado(request)})


def exibir(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    ja_eh_contato = perfil in perfil_logado.contatos.all()
    return render(request, 'perfis/perfil.html', {"perfil": perfil,'ja_eh_contato':ja_eh_contato})


def convidar(request, perfil_id):
    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_a_convidar)
    return redirect('index')


def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')


def get_perfil_logado(request):
    return Perfil.objects.get(id=1)

connectedin/usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from usuarios.forms import RegistrarUsuarioForm
from django.contrib.auth.models import User
from perfis.models import Perfil


class RegistrarUsuarioView(View):
    template_name = "usuarios/registrar.html"

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        # preenche o from
        form = RegistrarUsuarioForm(request.POST)

        # verifica se eh valido
        if form.is_valid():
            dados_form = form.data

            # cria o usuario
            cUsuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])

            # cria o perfil
            perfil = Perfil(nome=dados_form['nome'],
                            email=dados_form['email'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=cUsuario)

            # grava no banco
            perfil.save()

            # redireciona para index
            return redirect('index')

        # so chega aqui se nao for valido
        # vamos devolver o form para mostrar o formulario preenchido
        return render(request, self.template_name, {'form': form})

connectedin/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <title>ConnectedIn</title>
</head>
<body>
<div class="container">
    <div class="header">
        <ul class="nav nav-pills pull-right">
            <li><a href="{% url 'index' %}">{{ perfil_logado.nome }}</a></li>
            <li><a href="/logout/">Logout</a></li>
        </ul>
        <h3 class="text-muted">ConnectedIn</h3>
    </div>

    <div class="row content">
        {% block body %}
        {% endblock %}
    </div>
</div>
</body>
</html>

connectedin/templates/perfis/index.html
{% extends 'base.html' %}
{% block body %}
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>Todos os Perfis</strong>
            </div>
            <div class="panel-body">
                {% if perfis.exists %}
                    <ul>
                        {% for perfi in perfis %}
                            <li>
                                <a href="{% url 'exibir' perfi.id %}">{{ perfi.nome }} / {{ perfi.email }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p> Nenhum Perfil encontrado</p>
                {% endif %}
            </div>
        </div>

        <div class="panel panel-default">
            {% with  total_de_convites=perfil_logado.convites_recebidos.count %}
                {% if perfil_logado.convites_recebidos.count %}
                    <div class="panel-heading">
                        <strong>Você tem {{ total_de_convites }} Convite{{ total_de_convites | pluralize }}
                            aguardando aprovação</strong>
                    </div>
                    <ul class="list-group">
                        {% for convite in perfil_logado.convites_recebidos.all %}
                            <li class="list-group-item">
                                {{ convite.solicitante.nome }}
                                <a href="{% url 'aceitar' convite.id %}" class="pull-right">Aceitar</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="panel-body">
                        <p>Nenhum convite recebido :(</p>
                    </div>
                {% endif %}
            {% endwith %}
        </div>

        <div class="panel panel-default">
            {% with  total_de_contatos=perfil_logado.contatos.count %}
                {% if total_de_contatos %}
                    <div class="panel-heading">
                        <strong>Você tem {{ total_de_contatos }} Contato{{ total_de_contatos | pluralize }}</strong>
                    </div>
                    <ul class="list-group">
                        {% for contato in perfil_logado.contatos.all %}
                            <li class="list-group-item">
                                <a href="{% url 'exibir' contato.id %}">{{ contato.nome }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="panel-body">
                        <p>Você não Possui Contatos no momento :(</p>
                    </div>
                {% endif %}
            {% endwith %}
        </div>
    </div>
{% endblock %}

connectedin/templates/perfis/perfil.html
{% extends 'base.html' %}
{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h2 style="margin-top: 0">{{ perfil.nome }}</h2>
            <address>
                <strong>{{ perfil.nome_empresa }}</strong><br/>
                <abbr title="Telefone">Tel</abbr> {{ perfil.telefone }}<br/>
                <a href="mailto:{{ perfil.email }}">{{ perfil.email }}</a>
            </address>
            {% if ja_eh_contato %}
                <div class="well well-sm">
                    Vocês estão Conectados
                </div>
            {% else %}
                <a href="{% url 'convidar' perfil.id %}">Convidar</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

connectedin/templates/usuarios/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static 'styles/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/signin.css' %}">
    <title>ConnectedIn</title>
</head>
<body>
<div class="container">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

connectedin/templates/usuarios/registrar.html
{% extends 'base.html' %}
{% block body %}
    <form class="form-signin" action="{% url 'registrar' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Crie seu Usuário</h2>
        <input id="id_email" name="email" type="text" class="form-control" placeholder=" Email *" required>
        <input id="id_nome" name="nome" type="text" class="form-control" placeholder=" Nome *" required>
        <input id="id_senha" name="senha" type="password" class="form-control" placeholder=" Senha *" required>
        <input id="id_telefone" name="telefone" type="text" class="form-control" placeholder="Telefone *">
        <input id="id_nome_empresa" name="nome_empresa" type="text" class="form-control" placeholder="Nome Empresa *">
        <hr/>
        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Registrar</button>
    </form>
{% endblock %}